build: add knob to specify which plugins to build
Type: make
Change-Id: I6bd6df968577a4b5335f0604e02c2ea05d938355
Signed-off-by: Damjan Marion <damarion@cisco.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,6 +34,7 @@ OPTIONS:
   --native-only, -n       Only compile for Native CPU (no multiarch)
   --option, -o            Enable specific VPP options (fib8, fib16)
   --platform, -p          Specify target platform
+  --plugins, -P           Specify list of plugins to be built
   --prefix, -r            Specify prefix path (default: $prefix_path)
   --sanitize, -s          Enable sanitizer (mem)
   --verbose, -v           Verbose output of this script
@@ -86,6 +87,15 @@ while (( "$#" )); do
     -p|--platform)
       if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
         platform=$2
+        shift 2
+      else
+        echo "Error: Argument for $1 is missing" >&2
+        exit 1
+      fi
+      ;;
+    -P|--plugins)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        plugins=$2
         shift 2
       else
         echo "Error: Argument for $1 is missing" >&2
@@ -168,6 +178,8 @@ args+=("-DVPP_PLATFORM=${platform}")
 $native_only && args+=("-DVPP_BUILD_NATIVE_ONLY:BOOL=ON")
 
 $wipe && git clean -fdx --exclude=startup.\*
+
+[[ -v plugins ]] && args+=("-DVPP_PLUGINS=${plugins}")
 
 (
   $verbose && set -o xtrace
