gha: do not fail if unable to checkout the branch
This is to investigate/unblock the issue seen during the 26.02 RC1,
where the jobs fail on stable/2602 branch because of not being able to checkout it.
This change makes the failure non-fatal, and should have no effect on master branch.

Type: ci
Change-Id: I5aa7800975a11b382fbd0297a5db21cb26b57f44
Signed-off-by: Andrew Yourtchenko <ayourtch@gmail.com>

diff --git a/.github/actions/vpp-checkout-gerrit-change/action.yml b/.github/actions/vpp-checkout-gerrit-change/action.yml
--- a/.github/actions/vpp-checkout-gerrit-change/action.yml
+++ b/.github/actions/vpp-checkout-gerrit-change/action.yml
@@ -46,7 +46,7 @@ runs:
           echo "* Checkout $GERRIT_BRANCH ($GERRIT_REFSPEC)"
           echo "$TUI_LINE"
           cd "$WORKSPACE"
-          git checkout "$GERRIT_BRANCH"
+          git checkout "$GERRIT_BRANCH" || echo "WARNING: Could not checkout $GERRIT_BRANCH!"
           git fetch origin "$GERRIT_REFSPEC"
           git checkout FETCH_HEAD
           git show --stat
