gha: backport actions from master branch
Type: ci

Change-Id: Ibbbd59ac639593f130f1b8b4de84a934d4623c33
Signed-off-by: Dave Wallace <dwallacelf@gmail.com>

diff --git a/.github/actions/vpp-checkout-gerrit-change/action.yml b/.github/actions/vpp-checkout-gerrit-change/action.yml
--- a/.github/actions/vpp-checkout-gerrit-change/action.yml
+++ b/.github/actions/vpp-checkout-gerrit-change/action.yml
@@ -46,8 +46,8 @@ runs:
           echo "* Checkout $GERRIT_BRANCH ($GERRIT_REFSPEC)"
           echo "$TUI_LINE"
           cd "$WORKSPACE"
-          git checkout "$GERRIT_BRANCH"
-          git fetch origin "$GERRIT_REFSPEC"
+          git checkout "$GERRIT_BRANCH" || echo "WARNING: Could not checkout $GERRIT_BRANCH!"
+          git fetch --tags origin "$GERRIT_REFSPEC"
           git checkout FETCH_HEAD
           git show --stat
         } | tee "$LOG_DIR/checkout.log"
