gha: fetch also tags
Type: ci

Change-Id: I2d975129088cdeddffbc8f0b545a763ada5fc3af
Signed-off-by: Vratko Polak <vrpolak@cisco.com>
(cherry picked from commit 27fc2aa27f57c8f7055e8f1b6e5a9f41b0315873)

diff --git a/.github/actions/vpp-checkout-gerrit-change/action.yml b/.github/actions/vpp-checkout-gerrit-change/action.yml
--- a/.github/actions/vpp-checkout-gerrit-change/action.yml
+++ b/.github/actions/vpp-checkout-gerrit-change/action.yml
@@ -46,8 +46,13 @@ runs:
           echo "* Checkout $GERRIT_BRANCH ($GERRIT_REFSPEC)"
           echo "$TUI_LINE"
           cd "$WORKSPACE"
+<<<<<<< HEAD   (c95b61 gha: only checkout HEAD in merge job)
           git checkout "$GERRIT_BRANCH"
           git fetch origin "$GERRIT_REFSPEC"
+=======
+          git checkout "$GERRIT_BRANCH" || echo "WARNING: Could not checkout $GERRIT_BRANCH!"
+          git fetch --tags origin "$GERRIT_REFSPEC"
+>>>>>>> CHANGE (27fc2a gha: fetch also tags)
           git checkout FETCH_HEAD
           git show --stat
         } | tee "$LOG_DIR/checkout.log"
