gha: write console output to log files in verify checkstyle workflow
Type: ci

Change-Id: Ic3ca9d541b853c7b384081ea4d53547a06bbcf93
Signed-off-by: Dave Wallace <dwallacelf@gmail.com>

diff --git a/.github/workflows/vpp-verify-checkstyle.yml b/.github/workflows/vpp-verify-checkstyle.yml
--- a/.github/workflows/vpp-verify-checkstyle.yml
+++ b/.github/workflows/vpp-verify-checkstyle.yml
@@ -4,49 +4,10 @@ name: vpp-verify-checkstyle
 on:
   workflow_call:
     inputs:
-      GERRIT_BRANCH:
-        description: "Branch that change is against"
-        required: true
-        type: string
-      GERRIT_CHANGE_ID:
-        description: "The ID for the change"
-        required: true
-        type: string
-      GERRIT_CHANGE_NUMBER:
-        description: "The Gerrit number"
-        required: true
-        type: string
-      GERRIT_CHANGE_URL:
-        description: "URL to the change"
-        required: true
-        type: string
-      GERRIT_EVENT_TYPE:
-        description: "Type of Gerrit event"
-        required: true
-        type: string
-      GERRIT_PATCHSET_NUMBER:
-        description: "The patch number for the change"
-        required: true
-        type: string
-      GERRIT_PATCHSET_REVISION:
-        description: "The revision sha"
-        required: true
-        type: string
-      GERRIT_PROJECT:
-        description: "Project in Gerrit"
-        required: true
-        type: string
-      GERRIT_REFSPEC:
-        description: "Gerrit refspec of change"
-        required: true
-        type: string
       FDIO_NAMESPACE:
         description: "Executor Namespace (prod|sandbox)"
-        required: false
+        required: true
         type: string
-        default: prod
-  workflow_dispatch:
-    inputs:
       GERRIT_BRANCH:
         description: "Branch that change is against"
         required: true
@@ -83,6 +44,16 @@ on:
         description: "Gerrit refspec of change"
         required: true
         type: string
+      LOG_PATH:
+        description: "Sub-path to the log directory"
+        required: true
+        type: string
+      TIMESTAMP:
+        description: "Start verify timestamp"
+        required: true
+        type: string
+  workflow_dispatch:
+    inputs:
       FDIO_NAMESPACE:
         description: "Executor Namespace (prod|sandbox)"
         required: false
@@ -91,6 +62,50 @@ on:
           - sandbox
           - prod
         default: prod
+      GERRIT_BRANCH:
+        description: "Branch that change is against"
+        required: true
+        type: string
+      GERRIT_CHANGE_ID:
+        description: "The ID for the change"
+        required: true
+        type: string
+      GERRIT_CHANGE_NUMBER:
+        description: "The Gerrit number"
+        required: true
+        type: string
+      GERRIT_CHANGE_URL:
+        description: "URL to the change"
+        required: true
+        type: string
+      GERRIT_EVENT_TYPE:
+        description: "Type of Gerrit event"
+        required: true
+        type: string
+      GERRIT_PATCHSET_NUMBER:
+        description: "The patch number for the change"
+        required: true
+        type: string
+      GERRIT_PATCHSET_REVISION:
+        description: "The revision sha"
+        required: true
+        type: string
+      GERRIT_PROJECT:
+        description: "Project in Gerrit"
+        required: true
+        type: string
+      GERRIT_REFSPEC:
+        description: "Gerrit refspec of change"
+        required: true
+        type: string
+      LOG_PATH:
+        description: "Sub-path to the log directory"
+        required: true
+        type: string
+      TIMESTAMP:
+        description: "Start verify timestamp"
+        required: true
+        type: string
 
 env:
   GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
@@ -103,6 +118,13 @@ env:
   GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
   GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
   FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
+  TIMESTAMP: ${{ inputs.TIMESTAMP }}
+  LOG_PATH: ${{ inputs.LOG_PATH }}
+  WORKSPACE: /scratch/docker-build/vpp
+  FDIO_ARCH: x86_64
+  FDIO_CLASS: builder
+  FDIO_OS: ubuntu2404
+  TUI_LINE: "*******************************************************************"
 
 defaults:
   run:
@@ -119,14 +141,10 @@ jobs:
     runs-on:
       - self-hosted
       - nomad
-      - fdio:arch=x86_64
-      - fdio:class=builder
+      - fdio:arch=${{ env.FDIO_ARCH }}
+      - fdio:class=${{ env.FDIO_CLASS }}
       - fdio:namespace=${{ inputs.FDIO_NAMESPACE }}
-      - fdio:os=ubuntu2404
-
-    env:
-      WORKSPACE: /scratch/docker-build/vpp
-      TUI_LINE: "*******************************************************************"
+      - fdio:os=${{ env.FDIO_OS }}
 
     steps:
       - name: Setup Environment
@@ -155,69 +173,79 @@ jobs:
         run: |
           set -euxo pipefail
           cd $WORKSPACE
-          BUILD_EXT_DIR="build/external"
-          MATRIX_FILE="$BUILD_EXT_DIR/mlx_rdma_dpdk_matrix.txt"
-          PKGS_DIR="$BUILD_EXT_DIR/packages"
+          mkdir -p $LOG_DIR
+          {
+            BUILD_EXT_DIR="build/external"
+            MATRIX_FILE="$BUILD_EXT_DIR/mlx_rdma_dpdk_matrix.txt"
+            PKGS_DIR="$BUILD_EXT_DIR/packages"
 
-          if git show --stat | grep -q "$MATRIX_FILE" ; then
-              RDMA_CORE_VERSION="$(grep rdma-core_version $PKGS_DIR/rdma-core.mk | grep -v '(' | mawk '{print $3}')"
-              DPDK_VERSION="$(grep dpdk_version $PKGS_DIR/dpdk.mk | grep -v '(' | mawk '{print $3}')"
-              CURRENT_MATRIX="rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION"
-              if grep -q "$CURRENT_MATRIX" "$MATRIX_FILE"; then
-                  echo -e "$TUI_LINE\n* DPDK/RDMA-CORE matrix file update successfully verified\n$TUI_LINE"
-              else
-                  echo -e "$TUI_LINE\n* ERROR: 'rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION' not found in $MATRIX_FILE!\n$TUI_LINE"
-                  exit 1
-              fi
-          fi
+            if git show --stat | grep -q "$MATRIX_FILE" ; then
+                RDMA_CORE_VERSION="$(grep rdma-core_version $PKGS_DIR/rdma-core.mk | grep -v '(' | mawk '{print $3}')"
+                DPDK_VERSION="$(grep dpdk_version $PKGS_DIR/dpdk.mk | grep -v '(' | mawk '{print $3}')"
+                CURRENT_MATRIX="rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION"
+                if grep -q "$CURRENT_MATRIX" "$MATRIX_FILE"; then
+                    echo -e "$TUI_LINE\n* DPDK/RDMA-CORE matrix file update successfully verified\n$TUI_LINE"
+                else
+                    echo -e "$TUI_LINE\n* ERROR: 'rdma=$RDMA_CORE_VERSION dpdk=$DPDK_VERSION' not found in $MATRIX_FILE!\n$TUI_LINE"
+                    exit 1
+                fi
+            fi
+          } | tee $LOG_DIR/dpdk_rdma_matrix_check.log
 
-          make UNATTENDED=yes checkstyle
+          make UNATTENDED=yes checkstyle | tee $LOG_DIR/make_checkstyle.log
 
       - name: Run Test Checkstyle Scripts
         run: |
           set -euxo pipefail
           cd $WORKSPACE
-          make test-checkstyle
+          mkdir -p $LOG_DIR
+          make test-checkstyle | tee $LOG_DIR/test_checkstyle.log
 
       - name: Run API Checkstyle Scripts
         run: |
           set -euxo pipefail
           cd $WORKSPACE
-          VPP_CRC_CHECKER="extras/scripts/crcchecker.py"
-          VPP_CRC_CHECKER_CMD="$VPP_CRC_CHECKER --check-patchset"
+          mkdir -p $LOG_DIR
+          {
+            VPP_CRC_CHECKER="extras/scripts/crcchecker.py"
+            VPP_CRC_CHECKER_CMD="$VPP_CRC_CHECKER --check-patchset"
 
-          # API checker complains if the git repo is not clean.
-          # Help diagnosing those issues easier
-          git --no-pager diff
-          echo "Running $VPP_CRC_CHECKER_CMD"
-          if $VPP_CRC_CHECKER_CMD; then
-              echo "API check successful"
-          else
-              RET_CODE=$?
-              echo "API check failed: ret code $RET_CODE; please read https://wiki.fd.io/view/VPP/ApiChangeProcess and discuss with ayourtch@gmail.com if unsure how to proceed"
-              echo "::error file=.ci/scripts/vpp/crcchecker.py,line=1::API check FAILED for $GITHUB_REF. See run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-              exit $RET_CODE
-          fi
+            # API checker complains if the git repo is not clean.
+            # Help diagnosing those issues easier
+            git --no-pager diff
+            echo "Running $VPP_CRC_CHECKER_CMD"
+            if $VPP_CRC_CHECKER_CMD; then
+                echo "API check successful"
+            else
+                RET_CODE=$?
+                echo "API check failed: ret code $RET_CODE; please read https://wiki.fd.io/view/VPP/ApiChangeProcess and discuss with ayourtch@gmail.com if unsure how to proceed"
+                echo "::error file=.ci/scripts/vpp/crcchecker.py,line=1::API check FAILED for $GITHUB_REF. See run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+                exit $RET_CODE
+            fi
+          } | tee $LOG_DIR/api_checkstyle.log
 
       - name: Run Commit Message Checkstyle
         run: |
           set -euxo pipefail
           cd $WORKSPACE
-          echo "Running extras/scripts/check_commit_msg.sh"
-          extras/scripts/check_commit_msg.sh
+          mkdir -p $LOG_DIR
+          {
+            echo "Running extras/scripts/check_commit_msg.sh"
+            extras/scripts/check_commit_msg.sh
+          } | tee $LOG_DIR/commit_checkstyle.log
 
       - name: Run Docs Spell
         run: |
           set -euxo pipefail
           cd $WORKSPACE
-          make docs-spell
+          mkdir -p $LOG_DIR
+          make docs-spell | tee $LOG_DIR/docs_spelling_checkstyle.log
 
-      - name: Archive Checkstyle Logs
+      - name: Show Checkstyle Logs
         if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: vpp-checkstyle-logs-${{ inputs.GERRIT_BRANCH }}-rel-ubuntu2404-x86_64-${{ env.GERRIT_CHANGE_NUMBER }}-${{ env.GERRIT_PATCHSET_NUMBER }}
-          path: logs/
+        run: |
+          set -euxo pipefail
+          ls -l $LOG_DIR
 
       - name: Report Success
         if: success()
